baseURL = 'https://example.org/'
languageCode = 'zh-tw'
title = 'å·¥ä½œæ—¥èªŒ'
theme = "github-style"

[params]
  author = "é™³å‡æ˜Š"
  description = "é€™æ˜¯æˆ‘çš„æš‘æœŸå¯¦ç¿’å·¥ä½œæ—¥èªŒ"
  avatar = "https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/avatar.png"
  facebook = "é™³å‡æ˜Š"
  instagram = "BGB_CCH"
  twitter = "bgb"
  github = ""  # å¯å¡«ç©º
  email = "bgb20051207@gmail.com"
  url = ""
  headerIcon = "https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/github.png"
  location = "Taiwan"
  userStatusEmoji = "ğŸ˜€"
  enableSearch = true
  lastmod = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]