baseURL = 'https://bgb941207.github.io/work-log/'  # âœ… ä¿®æ­£é‡é»
languageCode = 'zh-tw'
title = 'å·¥ä½œæ—¥èªŒ'
theme = "github-style"
relativeURLs = true

[pagination]
  pagerSize = 99  # âœ… æ¸¬è©¦åˆ†é å¯æ”¹å°ä¸€é»ä»¥è§¸ç™¼ page/2

[params]
  author = "é™³å‡æ˜Š"
  description = "é€™æ˜¯æˆ‘çš„æš‘æœŸå¯¦ç¿’å·¥ä½œæ—¥èªŒ"
  avatar = "https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/avatar.png"
  facebook = "é™³å‡æ˜Š"
  instagram = "BGB_CCH"
  twitter = "bgb09446826"
  github = ""
  email = "bgb20051207@gmail.com"
  url = ""
  headerIcon = "https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/github.png"
  location = "Taiwan"
  userStatusEmoji = "ğŸ˜€"
  enableSearch = true
  lastmod = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = true
    style = "github"
